swagger: '2.0'
info:
  title: Sample App API
  description: Sample API built with Swagger
  version: 1.0.0
paths:
  /test:
    get:
      x-action: "r.expr([1,2,3])"
    post:
      parameters:
        - in: body
          name: test
          schema:
            $ref: "#/definitions/test"
      x-action: r.expr([1,2,3]).map(r.row.mul(2))
  /test/fellowship:
    get:
      x-action: r.db('test').table('fellowship')
    post:
      parameters:
        - in: body
          name: member
          schema:
            $ref: "#/definitions/fellowshipMember"
      x-action: r.db('test').table('fellowship').insert(params.member)
  /test/fellowship/:species:
    get:
      parameters:
        - {in: path, name: species, required: true, type: string}
      x-action: >
        r.db("test").table("fellowship").filter({species: params.species})
  /test/:n:
    get:
      parameters:
        - {in: path, name: n, type: string}
      x-action: r.expr(params.n)
  /messages:
    get:
      parameters:
      - {name: limit, in: query, type: number, default: 10}
      x-action: >
        r.db('chat').table('messages').orderBy(r.desc('time'))
         .limit(params.limit)
    post:
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              user: {type: string}
              text: {type: string}
            required: ["user", "text"]
      x-action: >
        r.db('chat').table('messages')
         .insert({user: params.user, text: params.text, time: r.now()})
  /messages/:limit:
    get:
      summary: Retrieve existing message history
      parameters:
      - {name: limit, in: path, type: number}
      x-action: >
        r.db('chat').table('messages')
         .orderBy(r.desc('time')).limit(params.limit)
x-collections:
  fellowship:
    path: "/api/lotr/fellowship"
    template:
      $ref: "#/x-templates/default"
    schema:
      $ref: "#/definitions/fellowshipMember"
    routes:
      /blah:
        get:
          x-action: r.expr([3,2,1]).map(r.row.mul(2))
        post:
          parameters:
            - in: body
              name: member
              schema: "@"
          x-action: r.table(collection).insert(params.member)
x-templates:
  default:
    /:
      get:
        x-action: r.table(collection)
      post:
        parameters:
          - in: body
            name: member
            schema: "@"
        x-action: r.table(collection).insert(params.member)
    /:id":
      get:
        parameters:
          - in: path
            name: id
            type: string
        x-action: r.table(collection).get(params.id)
      put:
        parameters:
          - in: path
            name: id
            type: string
          - in: body
            name: body
            schema: "@"
        x-action: r.table(collection).get(params.id).update(params.body)
      delete:
        parameters:
          - in: path
            name: id
            type: string
        x-action: r.table(collection).get(params.id).delete()
definitions:
  fellowshipMember:
    type: object
    properties:
      name: {type: string}
      species: {type: string}
    required: ["name", "species"]
    additionalProperties: false
  test:
    type: object
    properties:
      qwerty: {type: string}
